AllCops:
  DefaultFormatter: clang
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - Guardfile
    - kitchen-terraform.gemspec
    - spec/**/*.rb
Metrics/LineLength:
  Max: 120
Style/AccessorMethodName:
  Exclude:
    - lib/terraform/command_factory.rb
Style/AndOr:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Lambda:
  EnforcedStyle: lambda
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/WordArray:
  EnforcedStyle: brackets
