AllCops:
  DefaultFormatter: clang
  DisplayCopNames: true
  TargetRubyVersion: 2.4
Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/ParameterLists:
  Enabled: false
Style/AccessorMethodName:
  Exclude:
    - lib/terraform/command_factory.rb
Style/AndOr:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Lambda:
  EnforcedStyle: lambda
Style/MultilineBlockChain:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Not:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/WordArray:
  EnforcedStyle: brackets
